name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install

  build:
    name: build
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn build --since master

  test:
    name: test unit
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn build
      - run: yarn test --since master

  deploy-app:
    name: deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud sdk
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          service_account_key: ${{ secrets.GOOGLE_CLOUD_SA_KEY }}
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

      # Get .env file
      - name: secrets for light
        run: 'echo "$SECRETS_ENV" > services/light/.env'
        env:
          SECRETS_ENV: ${{ secrets.ENV }}

      # Get .npmrc file
      - name: registry configuration for light
        run: 'echo "$SECRETS_NPMRC" > services/light/.npmrc'
        env:
          SECRETS_ENV: ${{ secrets.NPMRC }}

      # Get .env file
      - name: secrets for kappa
        run: 'echo "$SECRETS_ENV" > services/kappa/.env'
        env:
          SECRETS_ENV: ${{ secrets.ENV }}

      # Get .npmrc file
      - name: registry configuration for kappa
        run: 'echo "$SECRETS_NPMRC" > services/kappa/.npmrc'
        env:
          SECRETS_ENV: ${{ secrets.NPMRC }}

      # Deploy to Google App Engine
      - name: deploy
        run: yarn deploy --since master
