name: kappa

on:
  push:
    paths:
      - "services/kappa/**"
      - ".github/workflows/kappa.yml"
    branches: [master]
  pull_request:
    paths:
      - "services/kappa/**"
      - ".github/workflows/kappa.yml"
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

defaults:
  run:
    working-directory: services/kappa

jobs:
  install-kappa:
    name: install kappa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-kappa
      - run: yarn install

  build-kappa:
    name: build kappa
    needs: install-kappa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-kappa
      - run: yarn install
      - run: yarn run build
      - uses: actions/upload-artifact@v2
        with:
          name: kappa-build
          path: services/kappa/dist

  test-kappa:
    name: test unit kappa
    needs: install-kappa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-kappa
      - run: yarn install
      - run: yarn test
